### ISSUE TITLE
compiling under Linux/Python3.6 fails

### ISSUE THREAD

**Issue by gridcutuser** [Borda/pyGridCut#3]
Hello,
I was testing GridCut under Linux, Python 2.7 and it seemed to work properly. Unfortunatelly, I need it to use under Linux+Python3.6 and Windows, but I have some troubles with compilling it. 
Do you have any working solution for that problem or can you advice me, what to do? 
Best regards,
Patryk

**Comment by Borda** [comment]
it seems that it is not compiling for any py3 for this moment...

**Comment by gridcutuser** [comment]
OK thank you for fast approval of my issue. 
Do you have any idea what to do with that? Or should I just wait and maybe new version will appear in future?
Best regards

**Comment by gridcutuser** [comment]
Thank you so much for help! For sure something changed but I didnt have enough time to test it properly :( I'll write the tests result in few days. Thank you for help:)

**Comment by Borda** [comment]
@gridcutuser I just added testing for several version of python to the [master](https://travis-ci.org/Borda/GridCut-python/builds/373972735) so you can simply have a try and see if the tests pass or not... :)

**Comment by Borda** [comment]
@gridcutuser hi how is it going? :)

**Comment by Borda** [comment]
@gridcutuser hi how is it going? :)

**Comment by Borda** [comment]
@gridcutuser hi how is it going? :)
